spring:
  application:
    name: hdtec-spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/heliohdd/environment-variable-repo.git

server:
  port: ${port:8888}          

